openapi: 3.0.3
info:
  title: ClipBin API
  description: |
    # ClipBin REST API Documentation
    
    ClipBin API provides a simple and secure way to programmatically interact with the ClipBin text sharing platform.
    
    ## 🚀 API Features
    
    - **Retrieve Clips**: Get clips by ID or search by name
    - **Create Clips**: Upload text clips with optional password protection
    - **No Authentication Required**: All API endpoints are public and don't require API keys
    
    ## 📝 Available Endpoints
    
    - `GET /api/get_data` - Retrieve clips with various search options
    - `POST /api/post_data` - Create new text clips
    - `GET /api` - Get API information and status
    
    ## 🔐 Security
    
    - No API keys required - all endpoints are public
    - Password-protected clips require the password parameter to access content
    - All data is validated and sanitized
    
    ## 📊 Content Limits
    
    - **Maximum clip size**: 1.5MB per clip
    - **Supported formats**: All text formats
    - **Expiration options**: day, week, 2 weeks, month, 6 months, year, or never
  version: 2.0.0
  contact:
    name: ClipBin Development Team
    url: https://github.com/yashksaini-coder/ClipBin
    email: support@clipbin.dev
  license:
    name: MIT License
    url: https://github.com/yashksaini-coder/ClipBin/blob/main/LICENSE
  termsOfService: https://clipbin.dev/terms

servers:
  - url: http://localhost:5000
    description: Local development server
  - url: https://api.clipbin.dev
    description: Production API server
  - url: https://staging-api.clipbin.dev
    description: Staging environment

tags:
  - name: Clip Retrieval
    description: Operations for retrieving and searching clips
  - name: Clip Management
    description: Operations for creating and managing clips
  - name: API Information
    description: General API information and status

paths:
  /api/get_data:
    get:
      tags:
        - Clip Retrieval
      summary: Retrieve clips
      description: |
        Retrieve text clips by ID, name, or alias. Supports searching public clips or accessing unlisted clips with specific IDs.
        
        **Search Options:**
        - **By ID**: Use `id` parameter to get a specific clip
        - **By Name**: Use `name` parameter to search clips by name (supports partial matching)
        - **By Alias**: Use `alias` parameter to get a clip by its custom alias
        - **No Parameters**: Returns an empty array (no error)
        
        **Privacy Options:**
        - Use `unlisted=true` with an ID to access unlisted (private) clips
        - Password-protected clips require the `pwd` parameter
      parameters:
        - name: id
          in: query
          description: Clip ID or alias to retrieve
          required: false
          schema:
            type: string
            example: "abc123"
        - name: name
          in: query
          description: Search clips by name (partial matching supported)
          required: false
          schema:
            type: string
            example: "my code snippet"
        - name: alias
          in: query
          description: Custom alias to retrieve a specific clip
          required: false
          schema:
            type: string
            example: "my-alias"
        - name: pwd
          in: query
          description: Password for password-protected clips
          required: false
          schema:
            type: string
            example: "secretpassword"
        - name: unlisted
          in: query
          description: Set to 'true' to search unlisted clips (requires ID)
          required: false
          schema:
            type: string
            enum: ['true', 'false']
            example: "true"
      responses:
        '200':
          description: Clips retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClipData'
              examples:
                single_clip:
                  summary: Single clip response
                  value:
                    - id: "abc123"
                      name: "My Code Snippet"
                      text: "console.log('Hello World');"
                      time: "01-10-2024 @ 14:30:25"
                empty_response:
                  summary: No clips found
                  value: []
        '400':
          description: Missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                Error: "Missing Parameters!"
        '401':
          description: Incorrect password for protected clip
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                Error: "Incorrect Password"
        '404':
          description: No clips found matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                Error: "No Data"

  /api/post_data:
    get:
      tags:
        - Clip Management
      summary: Get API info for clip creation
      description: Returns information about the clip creation endpoint
      responses:
        '200':
          description: API endpoint information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "POST data to this endpoint to create clips"
    
    post:
      tags:
        - Clip Management
      summary: Create a new clip
      description: |
        Create a new text clip with optional settings for privacy, expiration, and password protection.
        
        **Features:**
        - Password protection with encryption
        - Custom expiration times
        - Unlisted (private) clips
        - Custom aliases
        
        **Expiration Options:**
        - `day` - 24 hours
        - `week` - 7 days  
        - `twoweek` - 14 days
        - `month` - 30 days
        - `half` - 6 months
        - `year` - 365 days
        - `never` - No expiration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClipRequest'
            examples:
              basic_clip:
                summary: Basic public clip
                value:
                  name: "Hello World Example"
                  content: "console.log('Hello World');"
              protected_clip:
                summary: Password-protected clip
                value:
                  name: "Secret Code"
                  content: "const secret = 'hidden';"
                  pwd: "mypassword"
                  unlisted: "true"
                  remove: "week"
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateClipRequest'
            examples:
              form_submission:
                summary: Form-based submission
                value:
                  name: "My Script"
                  text: "print('Hello World')"
      responses:
        '201':
          description: Clip created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClipResponse'
              example:
                id: "abc123"
                Message: "Successfully added!"
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                missing_params:
                  summary: Missing parameters
                  value:
                    Error: "Missing Parameters!"
                server_error:
                  summary: Server error
                  value:
                    Error: "Couldn't add. Something went wrong."

  /api:
    get:
      tags:
        - API Information
      summary: Get API information
      description: Returns general information about the ClipBin API including available endpoints and usage examples
      responses:
        '200':
          description: API information page
          content:
            text/html:
              schema:
                type: string
                example: "<!DOCTYPE html><html>...</html>"
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "ClipBin API"
                  version:
                    type: string
                    example: "2.0.0"
                  endpoints:
                    type: array
                    items:
                      type: string
                    example: ["/api/get_data", "/api/post_data"]

components:
  schemas:
    ClipData:
      type: object
      properties:
        id:
          type: string
          description: Unique clip identifier
          example: "abc123g"
        name:
          type: string
          description: Clip title/name
          example: "My Python Script"
        text:
          type: string
          description: Clip content
          example: "print('Hello World')"
        time:
          type: string
          description: Creation timestamp
          example: "02-10-2025 @ 14:30:15"
      required:
        - id
        - name
        - text
        - time

    CreateClipRequest:
      type: object
      properties:
        name:
          type: string
          description: Title for the clip
          example: "My Code Snippet"
        content:
          type: string
          description: Content of the clip (for JSON requests)
          example: "console.log('Hello World');"
        text:
          type: string
          description: Content of the clip (for form requests)
          example: "console.log('Hello World');"
        pwd:
          type: string
          description: Optional password to protect the clip
          example: "secretpassword"
        unlisted:
          type: string
          enum: ['true', 'false']
          description: Make clip private (unlisted)
          example: "false"
        remove:
          type: string
          enum: ['day', 'week', 'twoweek', 'month', 'half', 'year', 'never']
          description: Auto-delete after specified time period
          example: "week"
      required:
        - name
      anyOf:
        - required: ["content"]
        - required: ["text"]

    CreateClipResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the created clip
          example: "abc123g"
        Message:
          type: string
          description: Success message
          example: "Successfully added!"
      required:
        - id
        - Message

    Error:
      type: object
      properties:
        Error:
          type: string
          description: Error message
          example: "Missing Parameters!"
      required:
        - Error
