name: General Issue
description: Create a general issue
title: "issue: "
labels: ["triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating this issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue here.
      placeholder: Provide details about the issue.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the issue here.
      placeholder: Screenshots, logs, etc.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](./CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: contributing
    attributes:
      label: Contribution Guidelines
      description: Please confirm you have read our [Contribution Guidelines](./CONTRIBUTING.md)
      options:
        - label: I have read and understood the Contribution Guidelines
          required: true
