name: CI
on: [push,pull_request]
jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkout@v5.0.0
         with:
           path: .
      - name: Setup Python
        uses: actions/setup-python@v6.0.0
      - name: Install Dependencies and Run
        run: |
            pip3 install -r requirements.txt
            python3 app.py || exit 1 &
            sleep 7
            curl http://127.0.0.1:5000 || exit 1
            
            


      
      
  
